// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/product/:productId": {
    params: {
      "productId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/product/:productId";
  };
  "pages/Landing.tsx": {
    id: "pages/Landing";
    page: "/";
  };
  "./pages/ProductDetail.tsx": {
    id: "pages/ProductDetail";
    page: "/product/:productId";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "pages/Landing": typeof import("./app/pages/Landing.tsx");
  "pages/ProductDetail": typeof import("./app/./pages/ProductDetail.tsx");
};