// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/product/:productId": {
    params: {
      "productId": string;
    };
  };
  "/cart": {
    params: {};
  };
  "/signin": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/shipping": {
    params: {};
  };
  "/payment": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/product/:productId" | "/cart" | "/signin" | "/register" | "/shipping" | "/payment" | "/*";
  };
  "pages/Landing.tsx": {
    id: "pages/Landing";
    page: "/";
  };
  "./pages/ProductDetail.tsx": {
    id: "pages/ProductDetail";
    page: "/product/:productId";
  };
  "./pages/Cart.tsx": {
    id: "pages/Cart";
    page: "/cart";
  };
  "./pages/SignIn.tsx": {
    id: "pages/SignIn";
    page: "/signin";
  };
  "./pages/Register.tsx": {
    id: "pages/Register";
    page: "/register";
  };
  "./pages/Shipping.tsx": {
    id: "pages/Shipping";
    page: "/shipping";
  };
  "./pages/Payment.tsx": {
    id: "pages/Payment";
    page: "/payment";
  };
  "./pages/NotFound.tsx": {
    id: "pages/NotFound";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "pages/Landing": typeof import("./app/pages/Landing.tsx");
  "pages/ProductDetail": typeof import("./app/./pages/ProductDetail.tsx");
  "pages/Cart": typeof import("./app/./pages/Cart.tsx");
  "pages/SignIn": typeof import("./app/./pages/SignIn.tsx");
  "pages/Register": typeof import("./app/./pages/Register.tsx");
  "pages/Shipping": typeof import("./app/./pages/Shipping.tsx");
  "pages/Payment": typeof import("./app/./pages/Payment.tsx");
  "pages/NotFound": typeof import("./app/./pages/NotFound.tsx");
};